version: '3.7'
services:
  proxy:
    container_name: m-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      laravel:
        ipv4_address: 172.40.0.2

  my-mariadb:
    container_name: m-mariadb
    build: ./mariadb
    image: custom-mariadb
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWROD=secret
      - MYSQL_DATABASE=LARAVELDB
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
#      - ./mariadb/conf:/etc/mysql
      - ./mariadb/data:/var/lib/mysql
#      - ./mariadb/log:/var/log/mysql
    networks:
      laravel:
        ipv4_address: 172.40.0.4

  my-laravel:
    container_name: m-laravel
    build: .
    image: custom-laravel
    volumes:
      - ./laravel-project:/root/laravel-project
    networks:
      laravel:
        ipv4_address: 172.40.0.3
    command: ["/bin/bash", "entrypoint"]

networks:
  laravel:
    external: true
