version: '3.7'
services:

  my-mariadb:
    container_name: m-mariadb
    build: ./mariadb
    image: custom-mariadb
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWROD=secret
      - MYSQL_DATABASE=LARAVELDB
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
      #      - ./mariadb/conf:/etc/mysql
      #      - ./mariadb/log:/var/log/mysql
    networks:
      laravel:
        ipv4_address: 172.40.0.4

  my-laravel:
    container_name: m-laravel
    build: .
    image: custom-laravel
    depends_on:
      - my-mariadb
    volumes:
      - ./laravel-project:/root/laravel-project
    networks:
      laravel:
        ipv4_address: 172.40.0.3
    command: ["/bin/bash", "entrypoint"]

  proxy:
    container_name: m-proxy
    image: nginx:latest
    depends_on:
      - my-laravel
    ports:
      - "80:80"
      - "82:80"
      - "443:443"
    links:
      - my-laravel
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      laravel:
        ipv4_address: 172.40.0.2

networks:
  laravel:
    external: true
