name: CI-CD

on:
  push:
    branches: [ master ]

jobs:
  test-php:
    name: Test/Lint PHP
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    defaults:
      run:
        shell: bash
        working-directory: ./laravel-project

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.4.3 # Use your PHP version
        extensions: mbstring, bcmath # Setup any required extensions for tests

    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Composer install
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database and Schemas
      run: php artisan migrate

    - name: Seed Database
      run: php artisan db:seed

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: pgsql
        DB_DATABASE: db_test
      run: ./vendor/bin/phpunit

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # Note that this needs both of the other steps to have completed successfully
    needs: [test-php] 
    steps:
    - uses: actions/checkout@v2
      # Deploy Code 
 