name: CI-CD # Give your workflow a name

on:
  push:
    branches: [ master ]

jobs:
  test-php:
    name: Test/Lint PHP
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./laravel-project

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.4.3 # Use your PHP version
        extensions: mbstring, bcmath # Setup any required extensions for tests

    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Composer install
      run: composer install
    - name: Run Tests
      run: ./vendor/bin/phpunit

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # Note that this needs both of the other steps to have completed successfully
    needs: [test-php] 
    steps:
    - uses: actions/checkout@v2
      # Deploy Code 
